---
name: "build"

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: "Авто релиз"
    runs-on: "windows-latest"
    strategy:
      matrix:
        dotnet-version: ['7.0.x']
    steps:
      - uses: actions/checkout@v2
      - name: Установка .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Установка зависимостей
        run: dotnet restore
      - name: Сборка решения
        run: dotnet build --configuration Release --no-restore
      - name: Упаковка решения
        run: dotnet publish -c release -r win10-x64 --self-contained /p:publishsinglefile=true /p:publishdir "./output/"
      - uses: vimtor/action-zip@v1
        with:
          files: output/
          dest: markus-win10-x64.zip
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            markus-win10-x64.zip
